inherit_from: .rubocop_todo.yml

AllCops:
  SuggestExtensions: false
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - "Gemfile"
    - "spec/*"
    - "spec/factories/*"
    - "bin/**/*"
    - "config/environments/*"
    - "config/puma.rb"
    - "db/schema.rb"

Layout/IndentationWidth:
  Enabled: false

Metrics/AbcSize:
  Max: 40
